load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "base",
    srcs = [
    ],
    hdrs = [
        "noncopyable.hpp",
    ],
    linkopts = ["-pthread"],
    visibility = ["//visibility:public"],
)
